Remove hard dependency on `reqwest/default-tls`
HenningHolmDE/hcloud-rust pull request #24
Opened 2024-10-03 10:24 UTC by DanielSidhion

The `reqwest` dependency was specified with all its default features, which [includes `default-tls`](https://github.com/seanmonstar/reqwest/blob/95fec09be9503d82c574f94e37dde0a814d1f850/Cargo.toml#L30). Even by using `hcloud-cloud` with its `rustls-tls` feature wouldn't remove the `default-tls` dependency.

```
[dependencies]
hcloud = { version = "0.20", default-features = false, features = ["rustls-tls"] }
```

```
$ cargo tree -e features -i reqwest
reqwest v0.12.8
├── reqwest feature "__rustls"
│   └── reqwest feature "rustls-tls-webpki-roots"
│       └── reqwest feature "rustls-tls"
│           └── hcloud feature "rustls-tls"
│               └── ...
...
├── reqwest feature "__tls"
│   ├── reqwest feature "__rustls" (*)
│   └── reqwest feature "default-tls"                        <- default-tls included here
│       └── reqwest feature "default"
│           └── hcloud v0.20.0
│               └── hcloud feature "rustls-tls" (*)          <- hcloud with rustls-tls here
...
```

This PR removes the default features of reqwest to avoid the `default-tls` feature. When doing this, we lose some of the other default features, so this PR also lists those features specifically to avoid losing them.

2024-10-06 13:58 UTC, HenningHolmDE requested changes
Thank you very much for the PR. I did not think about this back then when I added the features, but of course, it makes total sense to do it this way.

It would be great if you could fix the new deprecation warning, though. Then I'm happy to merge the PR.

(The failing checks are fine and can be ignored, the step running the examples is missing the Hetzner API key - I have to disable that step for PRs.)

2024-10-06 13:58 UTC, HenningHolmDE commented on Cargo.toml
> +reqwest = { version = "^0.12", default_features = false, features = [
```suggestion
reqwest = { version = "^0.12", default-features = false, features = [
```
to fix:
```warning: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition```.

2024-10-06 16:59 UTC, merged

2024-10-06 17:00 UTC, HenningHolmDE commented
@DanielSidhion Thank you for providing the improvement. Do you need this to be released soon for your use case of the crate?

2024-10-06 17:25 UTC, DanielSidhion commented
@HenningHolmDE no worries, thanks for the review! I'm currently using a [patch](https://github.com/DanielSidhion/hetzner-private-dns-sync/blob/3ae9261fec2ab77380c5a387ea1598439f2ba17a/hetzner-private-dns-sync/Cargo.toml#L18) on my Cargo.toml, so no big rush with a new release. I'll subscribe to new releases of `hcloud-rust` so I can clean up the patch in the future.

2024-10-25 09:59 UTC, HenningHolmDE commented
@DanielSidhion I just released v0.20.1 patching this, sorry for the delay. You should be able to get rid of you patch, now.

2024-10-25 11:47 UTC, DanielSidhion commented
No worries, thank you! Just updated things on my side to remove the patch :)